import type { Metadata } from "next";
import "./globals.css";
import { SandpackCSS } from "./(routes)/blog/[slug]/sandpack";
import { nunito, bricolageGrotesque } from "./fonts";
import { Navbar } from "./(components)/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bricolageGrotesque.variable} ${nunito.variable}`}
    >
      <head>
        <SandpackCSS />
      </head>
      {/*       <body className="antialiased max-w-2xl mb-40 flex flex-col md:flex-row mx-4 mt-8 lg:mx-auto">
       */}{" "}
      <body>
        {/*         <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
         */}{" "}
        <main>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
